<?php

/**
 * @file
 * egnyte_tabs module file.
 */

use \Drupal\file\Entity\File;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\media\Entity\Media;
use Drupal\node\Entity\Node;
use Drupal\paragraphs\Entity\Paragraph;
use Drupal\Core\Url;







/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function egnyte_tabs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.egnyte_tabs':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}


/**
 * Implements hook_theme().
 * Lets us define our paragraphs templates in this module.
 */
function egnyte_tabs_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__egnyte_tabs' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__egnyte_tabs_tab' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__egnyte_tabs__profiles' => [
      'base hook' => 'paragraph',
    ],

    'tabs' => [
      'base hook' => 'tabs',
    ],

  ];
}



function egnyte_tabs_preprocess_paragraph__egnyte_tabs(&$variables) {
 //Only load tabs.js when paragraph bundle is used
  $variables['#attached']['library'][] =  'egnyte/tabs-block-js';
  $paragraph = $variables['elements']['#paragraph'];

  $variables['tabs_module_path'] = drupal_get_path('module', 'egnyte_tabs');
  $tabs_tab = &drupal_static('egnyte_tabs_tab_header_function');
  $variables['tab_header'] =_tab_item($paragraph);

}


/*
 */
function egnyte_tabs_preprocess_paragraph__egnyte_tabs__profiles(&$variables) {

  $paragraph = $variables['elements']['#paragraph'];
  $node = $paragraph->field_egnyte_tabs__profiles->getValue();

  $variables['tab_card'] = _tab_profiles($node);
  $variables['job_title'] = $variables['tab_card'][0]['job_title'][0]['value'];
  $variables[ 'company'] = $variables['tab_card'][0]['company'][0]['value'];
  $variables['first_name'] = $variables['tab_card'][0]['first_name'][0]['value'];
  $variables['last_name'] = $variables['tab_card'][0]['last_name'][0]['value'];
  $variables['quote'] = $variables['tab_card'][0]['quote'][0]['value'];
  $variables['company_logo'] = !empty($variables['tab_card'][0]['company_logo']) ? $variables['tab_card'][0]['company_logo'] : '';
  $variables['link'] = $variables['tab_card'][0]['link_url'];
  $variables['link_title'] = $variables['tab_card'][0]['link_title'];

}




function _tab_profiles($nodes){

    $arr = array();

    if (is_array($nodes) || is_object($nodes)) {

      $nodes = Node::load($nodes[0]['target_id']);
      $arr[0]['job_title'] = $nodes->get('field_egnyte_profile__job_title')->getValue();
      $arr[0]['first_name'] = $nodes->get('field_egnyte_profile__fname')->getValue();
      $arr[0]['last_name'] = $nodes->get('field_egnyte_profile__lname')->getValue();
      $arr[0]['quote'] = $nodes->get('field_egnyte_profile__testimony')->getValue();
      $arr[0]['company'] = $nodes->get('field_egnyte_profile___company')->getValue();
      $arr[0]['link_title'] = isset( $nodes->get('field_egnyte_profile__tlink')->getValue()[0]['title'] ) ? $nodes->get('field_egnyte_profile__tlink')->getValue()[0]['title'] : '';

      $nid = isset($nodes->field_egnyte_profile__tlink->getValue()[0]['uri']) ? str_replace('entity:node/','', $nodes->field_egnyte_profile__tlink->getValue()[0]['uri']): '';
      $arr[0]['link_url'] = \Drupal::service('path_alias.manager')->getAliasByPath('/node/'.$nid);

    }


    return $arr;

  }





function _tab_item($paragraphs){

  $arr = array();

  if (is_array($paragraphs) || is_object($paragraphs)) {

    if ($paragraphs->getType() == "egnyte_tabs") {
      $entity = $paragraphs->field_egnyte_tabs__items->referencedEntities();
      foreach ( $entity as $key => $value ) {
        $arr[$key]['title']= $value->field_egnyte_tabs_tab___tab_titl->value;
        $arr[$key]['count'] = $key+1;

        if (!empty($value->field_egnyte_tabs_tab__icon->target_id)) {
            $entity = Media::load($value->field_egnyte_tabs_tab__icon->target_id);
            $arr[$key]['icon'] = file_create_url($entity->field_media_image->entity->getFileUri());
        }

      }
     // dump($paragraphs);
     /// dump($arr);
    }

  }

  return $arr;
}
