<?php

/**
 * @file
 * egnyte_four install file.
 */

function egnyte_hero_update_8001() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'egnyte_hero');
}

function egnyte_hero_update_8002() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'egnyte_hero');
}

function egnyte_hero_update_8003() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'egnyte_hero');
}
