<?php

/**
 * @file
 * egnyte_badges module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;






/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function egnyte_badges_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.egnyte_badges':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_theme().
 * Lets us define our paragraphs templates in this module.
 */
function egnyte_badges_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__egnyte_badges' => [
      'base hook' => 'paragraph',
    ],

  ];
}

function egnyte_badges_preprocess_paragraph__egnyte_badges(array &$variables) {
  $paragraph = $variables['elements']['#paragraph'];
  $variables['theme'] = $paragraph->get('field_egnyte_badges__theme')->value;
}