<?php

/**
 * @file
 * egnyte_site_builder module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;






/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function egnyte_site_builder_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.egnyte_site_builder':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_theme().
 * Lets us define our paragraphs templates in this module.
 */
function egnyte_site_builder_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__default' => [
      'base hook' => 'paragraph',
    ],
    'field__entity_reference_revisions' => [
      'base hook' => 'paragraph',
    ],
    
  ];
}

function limit_text($text, $limit) {
  if (str_word_count($text, 0) > $limit) {
      $words = str_word_count($text, 2);
      $pos   = array_keys($words);
      $text  = substr($text, 0, $pos[$limit]) . '...';
  }
  return $text;
}

function _careers_total($uuid){

  if ($cache = \Drupal::cache()->get('career_total--' . $uuid )) {
    return $cache->data;
  }
  else{

    $arr = array();
    $api = preg_replace("/\s+/", "", 'https://api.jobvite.com/api/v2/job?api=egnyte_jobfeed_api_key&sc=0def69f2df5ac3ff24e600d4c2ba00ab&jobStatus=Open&availableTo=external');
    $json = file_get_contents($api);

    $obj = json_decode($json);
    $arr[0]= $obj->total;
    if ($arr[0]) {
      \Drupal::cache()->set('career_total--' . $uuid, $arr[0], time() + 7200);
      return $arr[0];
    }
    else {
        return NULL;
    }
    

  }
  
}