<div class="{{ card_theme_class }} cards" data-id="{{ card_theme_class }}">
  <div class="{{ card_theme_grid }}">

    {%  if true in content.field_egnyte_cards__eyebrows[0] %}
    <h6 class="h6">{{ content.field_egnyte_cards__eyebrows[0] }}</h6>
    {% endif %}

    <h2 class="{{ card_theme_header }}">{{ content.field_egnyte_cards__title[0] }}</h2>

    {%  if true in content.field_egnyte_cards__eyebrows[0] %}
    <p class="mt-100 tc--dark p"> {{ content.field_egnyte_cards__text[0] }}</p>
    {% endif %}

    <div class="{{ card_theme_grid_row }}">
        {{ content.field_egnyte_cards__item }}
    </div>
  </div>
</div>
