<?php

/**
 * @file
 * egnyte_page install file.
 */ 

function egnyte_page_update_8001() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'egnyte_page');
}

function egnyte_page_update_8002() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'egnyte_page');
}

function egnyte_page_update_8003() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'egnyte_page');
}