<?php

/**
 * @file
 * egnyte_three_col_cta install file.
 */

function egnyte_three_col_cta_update_8001() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'egnyte_three_col_cta');
}

function egnyte_three_col_cta_update_8002()
{
  \Drupal::service('config.installer')->installDefaultConfig('module', 'egnyte_three_col_cta');
}

function egnyte_three_col_cta_update_8003()
{
  \Drupal::service('config.installer')->installDefaultConfig('module', 'egnyte_three_col_cta');
}
