<?php

/**
 * @file
 * egnyte_careers_feed module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\Entity\Node;
use Drupal\taxonomy\Entity\Term;
use \Drupal\file\Entity\File;





/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function egnyte_careers_feed_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.egnyte_careers_feed':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_theme().
 * Lets us define our paragraphs templates in this module.
 */
function egnyte_careers_feed_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__egnyte_careers_feed' => [
      'base hook' => 'paragraph',
    ],

  ];
}

function egnyte_careers_feed_preprocess_paragraph__egnyte_careers_feed(array &$variables) {
  $paragraph = $variables['elements']['#paragraph'];
  
  $variables['careers_feed'] = _careers_feed();
  print_r($variables['careers_feed']);
}

function _careers_feed()
{
/*   if ($cache = \Drupal::cache()->get('hp_news_feed--' . $id . '-' . $range)) {
    return $cache->data;
  } else { */
    $url = "https://api.jobvite.com/api/v2/job?api=egnyte_jobfeed_api_key&sc=0def69f2df5ac3ff24e600d4c2ba00ab&jobStatus=Open&availableTo=Internal";
  
    $result = file_get_contents($url);
    $array = json_decode($result, TRUE);
   // print_r($array['requisitions'][0]['firstname']);

   // foreach ($array as  $value){
     // $arr['description'] = $value['requisitions'][0];
      //$arr[$num]['description'] = $value->briefDescription;
     // var_dump($key);
      //var_dump($value);

  //  }
 
    return $array['requisitions'][0];
  }
