<?php

/**
 * @file
 * egnyte_carousel_cta module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\Entity\Node;
use Drupal\media\Entity\Media;


/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function egnyte_carousel_cta_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.egnyte_carousel_cta':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_theme().
 * Lets us define our paragraphs templates in this module.
 */
function egnyte_carousel_cta_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__egnyte_carousel_cta' => [
      'base hook' => 'paragraph',
    ],

    'paragraph__egnyte_carousel_cta__widget' => [
      'base hook' => 'paragraph',
    ],

  ];
}
 
function egnyte_carousel_cta_preprocess_paragraph__egnyte_carousel_cta__widget(&$variables) {
  
  $paragraph = $variables['elements']['#paragraph'];


  if ($paragraph->hasField('field_egnyte_carousel_cta__image')) {
    $bkrd_image = $paragraph->get('field_egnyte_carousel_cta__image')->getValue();
    if ($bkrd_image && !empty($bkrd_image)) {
      $entity = Media::load($bkrd_image[0]['target_id']);
      if (isset($entity->field_media_image->entity)) {
        $variables['image'] = file_create_url($entity->field_media_image->entity->getFileUri());
      }
    }

}


} 