<?php

/**
 * @file
 * egnyte_cta install file.
 */

function egnyte_two_column_update_8001() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'egnyte_two_column');
}

function egnyte_two_column_update_8002() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'egnyte_two_column');
}

function egnyte_two_column_update_8003() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'egnyte_two_column');
}