<?php

/**
 * @file
 * egnyte_news module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\Entity\Node;
use Drupal\media\Entity\Media;






/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function egnyte_news_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.egnyte_news':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_theme().
 * Lets us define our paragraphs templates in this module.
 */
function egnyte_news_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__egnyte_news' => [
      'base hook' => 'paragraph',
    ],

  ];
}

function egnyte_news_preprocess_paragraph__egnyte_news(array &$variables) {
  $paragraph = $variables['elements']['#paragraph'];
  $node = $paragraph->field_egnyte_news__articles->getValue();
  $variables['news_cards'] = _news_cards($node);
}


function _news_cards($node){
    $arr=[];
    $arr1=[];
    if (!empty($node) ){
    foreach($node as $key => $value){
  //    var_dump($value['target_id']);
     $arr1['target_id'][$key] = $value['target_id'];
     $nodes = Node::loadMultiple($arr1['target_id']);
      foreach ($nodes as $num => $value){
        if (!empty($nodes)){
            $arr[$num]['title'] = $value->get('title')->value;
            $arr[$num] ['body']= limit_text(strip_tags($value->body->get(0)->value), 20);
            $arr[$num]['date']= $value->get('field_newsletter_date')->value;
            $arr[$num]['link']= $value->get('field_story_link')->getValue();

            if ($value->hasField('field_news_logo')) {
              $bkrd_image = $value->get('field_news_logo')->getValue();

               if ($bkrd_image && !empty($bkrd_image)) {
                  $entity = Media::load($bkrd_image[0]['target_id']);
                  $arr[$num]['image_alt'] = $bkrd_image[0]['alt'] ;
                  $arr[$num]['image'] = file_create_url($entity->field_media_image->entity->getFileUri());

              }
            }

        }
      }
    }
  }
  return $arr;
}
